stages:
  - build

build_job:
  stage: build
  image: eda_env:v1.0
  tags:
    - eda
  script:
    - git submodule update --init --recursive
    - mkdir build
    - cd build
    - cmake -DARCH=xilinx ..
    - make -j20
    - cd ..
    - python3 xilinx/python/bbaexport.py --device xc7a35tfgg484-2 --bba xc7a35tfgg484-2.bba
    - ./build/bbasm  --l xc7a35tfgg484-2.bba xc7a35tfgg484-2.bin
    - python3 xilinx/python/bbaexport.py --device xc7a100tfgg484-2 --bba xc7a100tfgg484-2.bba
    - ./build/bbasm  --l xc7a100tfgg484-2.bba xc7a100tfgg484-2.bin
    - python3 xilinx/python/bbaexport.py --device xc7a200tfbg484-2 --bba xc7a200tfbg484-2.bba
    - ./build/bbasm  --l xc7a200tfbg484-2.bba xc7a200tfbg484-2.bin
    - python3 xilinx/python/bbaexport.py --device xc7k160tffg676-2 --bba xc7k160tffg676-2.bba
    - ./build/bbasm  --l xc7k160tffg676-2.bba xc7k160tffg676-2.bin
    
    - mv build/nextpnr-xilinx .
  artifacts:
    paths:
      - nextpnr-xilinx
      - xc7k160tffg676-2.bin
      - xc7a200tfbg484-2.bin
      - xc7a100tfgg484-2.bin
      - xc7a35tfgg484-2.bin
    expire_in: 2 months
